in:
  type: file
  path_prefix: example/example.jsonl
  parser:
    type: json
out:
  type: bigquery
  mode: replace
  auth_method: json_key
  json_keyfile: /tmp/your-project-000.json
  dataset: your_dataset_name
  table: your_table_name_%Y%m%d
  source_format: NEWLINE_DELIMITED_JSON
  auto_create_table: true
  schema_file: example/config_json_record_schema.json
  column_options:
  - {name: "record", type: "RECORD"}
