in:
  type: file
  path_prefix: example/example.csv
  parser:
    type: csv
    charset: UTF-8
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: timestamp,   type: timestamp, format: "%Y-%m-%d %H:%M:%S.%N", timezone: "+09:00"}
      - {name: string_date, type: string}
      - {name: foo,         type: string}
      - {name: bar,         type: string}
      - {name: id,          type: long}
      - {name: name,        type: string}
      - {name: score,       type: double}
out:
  type: bigquery
  mode: append
  auth_method: json_key
  json_keyfile: /tmp/your-project-000.json
  dataset: your_dataset_name
  table: your_table_name_%Y%m%d
  compression: GZIP
  source_format: CSV
  auto_create_table: true
  schema_file: example/schema.json
  delete_from_local_when_job_end: false
